export const defaultOptions: Required<Options> = {
  color: "yellow",
  debug: false,
  duration: 3000,
  enforceCapitalization: true,
  format: "rgba4444",
  fps: 20,
  maxMessageLength: 80,
  motion: "none",
  pattern: [],
  replacement: "",
  scale: 2,
  suffix: ":",
  version: "osrs",
};
